datasets:
  dev: data/dev.csv # dev set is named "tet" in files
  test: datasets/test_dataset.csv # local test set until official test is announced

stage1:
  - name: t1_bert_en_base_lora16_fixed_defaultHead_head_WCE_originalData_atomic
    checkpoint: models/encoders/s1_encoder_adaptation/stage1_trained_models/t1_bert_en_base_lora16_fixed_defaultHead_head_WCE_originalData_atomic
  - name: t1_mbert_multi_base_unfreezing25_fixed_defaultHead_head_WCE_originalData_atomic
    checkpoint: models/encoders/s1_encoder_adaptation/stage1_trained_models/t1_mbert_multi_base_unfreezing25_fixed_defaultHead_head_WCE_originalData_atomic
  - name: t1_deberta_en_base_unfreezing25_fixed_defaultHead_head_WCE_originalData_atomic
    checkpoint: models/encoders/s1_encoder_adaptation/stage1_trained_models/t1_deberta_en_base_unfreezing25_fixed_defaultHead_head_WCE_originalData_atomic
  - name: t1_mdeberta_multi_base_unfreezing25_fixed_defaultHead_head_WCE_originalData_atomic
    checkpoint: models/encoders/s1_encoder_adaptation/stage1_trained_models/t1_mdeberta_multi_base_unfreezing25_fixed_defaultHead_head_WCE_originalData_atomic
  - name: t1_roberta_en_base_unfreezing75_fixed_defaultHead_head_WCE_originalData_atomic
    checkpoint: models/encoders/s1_encoder_adaptation/stage1_trained_models/t1_roberta_en_base_unfreezing75_fixed_defaultHead_head_WCE_originalData_atomic
  - name: t1_roberta_en_large_unfreezing25_fixed_defaultHead_head_WCE_originalData_atomic
    checkpoint: models/encoders/s1_encoder_adaptation/stage1_trained_models/t1_roberta_en_large_unfreezing25_fixed_defaultHead_head_WCE_originalData_atomic
  - name: t1_xlmr_multi_base_unfreezing25_fixed_defaultHead_head_WCE_originalData_atomic
    checkpoint: models/encoders/s1_encoder_adaptation/stage1_trained_models/t1_xlmr_multi_base_unfreezing25_fixed_defaultHead_head_WCE_originalData_atomic
  - name: t1_xlmr_multi_large_unfreezing25_fixed_defaultHead_head_WCE_originalData_atomic
    checkpoint: models/encoders/s1_encoder_adaptation/stage1_trained_models/t1_xlmr_multi_large_unfreezing25_fixed_defaultHead_head_WCE_originalData_atomic

# Best out of Stage 2 uses the best available models up to stage 2 (not necessarily trained in stage 2).
stage2:
  - name: t1_bert_en_base_lora16_fixed_defaultHead_head-tail_WCE_originalData_atomic
    checkpoint: models/encoders/s2_representation_classification/stage2_trained_models/t1_bert_en_base_lora16_fixed_defaultHead_head-tail_WCE_originalData_atomic
  - name: t1_mbert_multi_base_unfreezing25_fixed_defaultHead_head_WCE_originalData_atomic
    checkpoint: models/encoders/s1_encoder_adaptation/stage1_trained_models/t1_mbert_multi_base_unfreezing25_fixed_defaultHead_head_WCE_originalData_atomic
  - name: t1_deberta_en_base_unfreezing25_fixed_multiLayerHead_head-tail_WCE_originalData_atomic
    checkpoint: models/encoders/s2_representation_classification/stage2_trained_models/t1_deberta_en_base_unfreezing25_fixed_multiLayerHead_head-tail_WCE_originalData_atomic
  - name: t1_mdeberta_multi_base_unfreezing25_fixed_avgPoolHead_head_WCE_originalData_atomic
    checkpoint: models/encoders/s2_representation_classification/stage2_trained_models/t1_mdeberta_multi_base_unfreezing25_fixed_avgPoolHead_head_WCE_originalData_atomic
  - name: t1_roberta_en_base_unfreezing75_fixed_avgPoolHead_head-tail_WCE_originalData_atomic
    checkpoint: models/encoders/s2_representation_classification/stage2_trained_models/t1_roberta_en_base_unfreezing75_fixed_avgPoolHead_head-tail_WCE_originalData_atomic
  - name: t1_roberta_en_large_unfreezing25_fixed_avgPoolHead_head_WCE_originalData_atomic
    checkpoint: models/encoders/s2_representation_classification/stage2_trained_models/t1_roberta_en_large_unfreezing25_fixed_avgPoolHead_head_WCE_originalData_atomic
  - name: t1_xlmr_multi_base_unfreezing25_fixed_defaultHead_head_WCE_originalData_atomic
    checkpoint: models/encoders/s1_encoder_adaptation/stage1_trained_models/t1_xlmr_multi_base_unfreezing25_fixed_defaultHead_head_WCE_originalData_atomic
  - name: t1_xlmr_multi_large_unfreezing25_fixed_defaultHead_head-tail_WCE_originalData_atomic
    checkpoint: models/encoders/s2_representation_classification/stage2_trained_models/t1_xlmr_multi_large_unfreezing25_fixed_defaultHead_head-tail_WCE_originalData_atomic

# Best out of Stage 3 uses the best available models up to stage 3 (not necessarily trained in stage 3).
stage3:
  - name: t1_bert_en_base_lora16_fixed_defaultHead_head-tail_WCE_originalData_atomic
    checkpoint: models/encoders/s2_representation_classification/stage2_trained_models/t1_bert_en_base_lora16_fixed_defaultHead_head-tail_WCE_originalData_atomic
  - name: t1_mbert_multi_base_unfreezing25_fixed_defaultHead_head_WCE_originalData_atomic
    checkpoint: models/encoders/s1_encoder_adaptation/stage1_trained_models/t1_mbert_multi_base_unfreezing25_fixed_defaultHead_head_WCE_originalData_atomic
  - name: t1_deberta_en_base_unfreezing25_fixed_multiLayerHead_head-tail_WCE_originalData_atomic
    checkpoint: models/encoders/s2_representation_classification/stage2_trained_models/t1_deberta_en_base_unfreezing25_fixed_multiLayerHead_head-tail_WCE_originalData_atomic
  - name: t1_mdeberta_multi_base_unfreezing25_fixed_avgPoolHead_head_WCE_originalData_atomic
    checkpoint: models/encoders/s2_representation_classification/stage2_trained_models/t1_mdeberta_multi_base_unfreezing25_fixed_avgPoolHead_head_WCE_originalData_atomic
  - name: t1_roberta_en_base_unfreezing75_fixed_avgPoolHead_head-tail_WCE_originalData_atomic
    checkpoint: models/encoders/s2_representation_classification/stage2_trained_models/t1_roberta_en_base_unfreezing75_fixed_avgPoolHead_head-tail_WCE_originalData_atomic
  - name: t1_roberta_en_large_unfreezing25_fixed_avgPoolHead_head_WCE_originalData_atomic
    checkpoint: models/encoders/s2_representation_classification/stage2_trained_models/t1_roberta_en_large_unfreezing25_fixed_avgPoolHead_head_WCE_originalData_atomic
  - name: t1_xlmr_multi_base_unfreezing25_fixed_defaultHead_head_WCE_originalData_atomic
    checkpoint: models/encoders/s1_encoder_adaptation/stage1_trained_models/t1_xlmr_multi_base_unfreezing25_fixed_defaultHead_head_WCE_originalData_atomic
  - name: t1_xlmr_multi_large_unfreezing25_fixed_defaultHead_head-tail_WCE_originalData_atomic
    checkpoint: models/encoders/s2_representation_classification/stage2_trained_models/t1_xlmr_multi_large_unfreezing25_fixed_defaultHead_head-tail_WCE_originalData_atomic

# Best out of Stage 4 uses the best available models up to stage 4 (not necessarily trained in stage 4).
stage4:
  - name: t1_bert_en_base_lora16_fixed_defaultHead_head-tail_WCE_originalData_atomic
    checkpoint: models/encoders/s2_representation_classification/stage2_trained_models/t1_bert_en_base_lora16_fixed_defaultHead_head-tail_WCE_originalData_atomic
  - name: t1_mbert_multi_base_unfreezing25_fixed_defaultHead_head_WCE_augmentedData_enriched
    checkpoint: models/encoders/s1_encoder_adaptation/stage1_trained_models/t1_mbert_multi_base_unfreezing25_fixed_defaultHead_head_WCE_originalData_atomic
  - name: t1_deberta_en_base_unfreezing25_fixed_multiLayerHead_head-tail_augmentedData_enriched
    checkpoint: models/encoders/s4_data_augmentation/stage4_trained_models/t1_deberta_en_base_unfreezing25_fixed_multiLayerHead_head-tail_augmentedData_enriched
  - name: t1_mdeberta_multi_base_unfreezing25_fixed_avgPoolHead_head_WCE_originalData_atomic
    checkpoint: models/encoders/s2_representation_classification/stage2_trained_models/t1_mdeberta_multi_base_unfreezing25_fixed_avgPoolHead_head_WCE_originalData_atomic
  - name: t1_roberta_en_base_unfreezing75_fixed_avgPoolHead_head-tail_WCE_originalData_atomic
    checkpoint: models/encoders/s2_representation_classification/stage2_trained_models/t1_roberta_en_base_unfreezing75_fixed_avgPoolHead_head-tail_WCE_originalData_atomic
  - name: t1_roberta_en_large_unfreezing25_fixed_avgPoolHead_head_WCE_originalData_atomic
    checkpoint: models/encoders/s2_representation_classification/stage2_trained_models/t1_roberta_en_large_unfreezing25_fixed_avgPoolHead_head_WCE_originalData_atomic
  - name: t1_xlmr_multi_base_unfreezing25_fixed_defaultHead_head_WCE_augmentedData_atomic
    checkpoint: models/encoders/s1_encoder_adaptation/stage1_trained_models/t1_xlmr_multi_base_unfreezing25_fixed_defaultHead_head_WCE_originalData_atomic
  - name: t1_xlmr_multi_large_unfreezing25_fixed_defaultHead_head-tail_WCE_originalData_atomic
    checkpoint: models/encoders/s2_representation_classification/stage2_trained_models/t1_xlmr_multi_large_unfreezing25_fixed_defaultHead_head-tail_WCE_originalData_atomic
