stage: s2_representation_classification

truncation_modes:
  - head
  - head_tail

classification_heads:
  - default
  - mlp
  - avgpool

runs:
  - model: bert-base-uncased
    script: stage2_train_lora.py
    lora_rank: 16
    lang: en

  - model: bert-base-multilingual-cased
    script: stage2_train_freeze.py
    unfreeze_ratio: 0.25
    lang: multi

  - model: microsoft/deberta-v3-base
    script: stage2_train_freeze.py
    unfreeze_ratio: 0.25
    lang: en

  - model: microsoft/mdeberta-v3-base
    script: stage2_train_freeze.py
    unfreeze_ratio: 0.25
    lang: multi

  - model: roberta-base
    script: stage2_train_freeze.py
    unfreeze_ratio: 0.75
    lang: en

  - model: roberta-large
    script: stage2_train_freeze.py
    unfreeze_ratio: 0.25
    lang: en

  - model: FacebookAI/xlm-roberta-base
    script: stage2_train_freeze.py
    unfreeze_ratio: 0.25
    lang: multi

  - model: FacebookAI/xlm-roberta-large
    script: stage2_train_freeze.py
    unfreeze_ratio: 0.25
    lang: multi
