# Stage 3: final representation classification
# Truncation + classification head will be fixed per model after Stage 2 analysis
# Loss variants are explored for each final configuration

stage: s3_loss&regularization

loss_functions:
  - WCE
  - Focal

dropout:
  - 0.1 #default
  - 0.3

runs:
  - model: microsoft/deberta-v3-base
    script: stage3_train_freeze.py
    unfreeze_ratio: 0.25
    truncation: head_tail        # head | head_tail
    classification_head: mlp   # default | mlp | avgpool

  - model: microsoft/mdeberta-v3-base
    script: stage3_train_freeze.py
    unfreeze_ratio: 0.25
    truncation: head
    classification_head: avgpool

  - model: bert-base-uncased
    script: stage3_train_lora.py
    lora_rank: 16
    truncation: head_tail
    classification_head: default

  - model: bert-base-multilingual-cased
    script: stage3_train_freeze.py
    unfreeze_ratio: 0.25
    truncation: head
    classification_head: default

  - model: roberta-base
    script: stage3_train_freeze.py
    unfreeze_ratio: 0.75
    truncation: head_tail
    classification_head: avgpool

  - model: roberta-large
    script: stage3_train_freeze.py
    unfreeze_ratio: 0.25
    truncation: head
    classification_head: avgpool

  - model: FacebookAI/xlm-roberta-base
    script: stage3_train_freeze.py
    unfreeze_ratio: 0.25
    truncation: head
    classification_head: default

  - model: FacebookAI/xlm-roberta-large
    script: stage3_train_freeze.py
    unfreeze_ratio: 0.25
    truncation: head_tail
    classification_head: default
